version: "3.7"
services:
  expose:
    image: jemmyphan/expose-server:0.0.1
    ports:
      - ${PORT}:${PORT}
    environment:
      port: ${PORT}
      domain: ${DOMAIN}
      username: ${ADMIN_USERNAME}
      password: ${ADMIN_PASSWORD}
    restart: always
    volumes:
      - ./database/expose.db:/root/.expose
      - ./builds:/src/builds/
